In [4]:
from pax.envs.in_the_matrix_nplayer2 import EnvState, EnvParams, InTheMatrix
import jax
import jax.numpy as jnp
def func(x, y):
    return x + y
experimental_function = jax.vmap(jax.vmap(func, (None, 0), 0), (0, None), 0)
z = experimental_function(jnp.array([5,6,7]), jnp.array([5,6,7]))
z
a = jnp.array([[True, False, False],
              [False, False, False],
              [False, True, False]])
a.any(axis=1)

def func(x, y, z, m1, m2):
    pos = jnp.where(
        z * m1 *m2,
        x,
        y
    )
    return pos
x = jnp.ones((3,2))+2
y = jnp.ones((3,2))+3
collision = jnp.array([[False, True],
               [True, True],
               [True, True]])

moves = jnp.array([True, True, True])
move_matrix = jnp.array([[True, True],
                        [True, True],
                        [True, True]])
vmap_func = jax.vmap(jax.vmap(func, (None, None, 0, None, 0), 0), (0, 0, 0, 0, 0), 0)
pos = vmap_func(x, y, collision, moves, move_matrix)
print(pos)
print(pos.shape)
# num_inner_steps = 150
# num_outer_steps = 1
# num_agents=8

# rng = jax.random.PRNGKey(0)
# env = InTheMatrix(num_inner_steps, num_outer_steps, num_agents,  True)
# num_actions = env.action_space().n

# params = EnvParams(
#     payoff_matrix=jnp.array([[[3, 0], [5, 1]], [[3, 5], [0, 1]]]),
#     freeze_penalty=5,
# )
# obs, old_state = env.reset(rng, params)


[[[4. 4.]
  [3. 3.]]

 [[3. 3.]
  [3. 3.]]

 [[3. 3.]
  [3. 3.]]]
(3, 2, 2)
